id: IA4D24540
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T04:18:42+00:00'
last_modified: '2022-06-08T13:32:32.806520+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W6468
  title: འཇམ་དབྱངས་སྤྲུལ་པའི་གླེགས་བམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5DA0:
      image_group_id: I1714
      title: ''
      total_pages: 218
      order: 1
      base_file: 5DA0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
