id: P010429
initial_creation_type: ocr
source_metadata:
  id: bdr:W6468
  title: འཇམ་དབྱངས་སྤྲུལ་པའི་གླེགས་བམ
  author: ''
  volumes:
    f687dabbe72344c19c65357b9ac74db5:
      image_group_id: I1714
      title: ''
      volume_number: 1
      total_pages: 218
      base_file: v001.txt
